CREATE TABLE `assessment_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customer_name` varchar(255) NOT NULL,
	`customer_email` varchar(320) NOT NULL,
	`num_instances` int,
	`currently_running` varchar(50),
	`current_version` varchar(50),
	`current_edition` varchar(50),
	`current_deployment` varchar(100),
	`current_deployment_type` varchar(50),
	`licensing_model` varchar(100),
	`software_assurance` varchar(50),
	`purchase_date` varchar(50),
	`target_version` varchar(50),
	`target_edition` varchar(50),
	`hadr_requirements` varchar(100),
	`migration_approach` varchar(100),
	`recommendation_summary` text,
	`deployment_model` varchar(100),
	`licensing_option` varchar(100),
	`recommended_instances` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessment_records_id` PRIMARY KEY(`id`)
);
